version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8008:80"
    networks: 
      - production-network
    depends_on:
      - "reactjs"

  reactjs:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: react
    ports:
      - "3000"
    networks:
      - production-network

networks: 
  production-network:
    driver: bridge
