version: '3'
services:
  react_app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: dev/node
    container_name: react-application
    ports:
      - "8005:3000"
    networks:
      - production-network

networks:
  production-network:
    driver: bridge